version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "linaizhong/kuai-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "linaizhong/kuai-frontend"
    ports:
      - "3000:3000"
    links:
      - "backend"